# btarg device settings, YAML
# With exception of 'general', each top level key defines a new ioc for that device
general:
    prefix: TGT:BTARG
    log_dir: 'logs'   # path of logs directory
    epics_addr_list: '129.57.163.255'
    #epics_addr_list: '127.255.255.255'
    #epics_beacon_addr_list: '127.255.255.255'
    delay: 1
status:   # SoftIOC to switch between target states
    module: 'devices.status_ioc'
    autostart: True
    delay: 1
    prod_pv: True   # turn on production status PV
    full_status:    # list of PVs that indicate full state when all not alarming
        - TGT:BTARG:Cell_Top_TI
        - TGT:BTARG:Cell_Bottom_TI
        - TGT:BTARG:Target_Supply_PI
lakeshore_336:
    module: 'devices.ls336'
    autostart: True          # Should IOC Manager try to start this?
    ip: '192.168.1.118'
    port: '7777'
    timeout: 2
    delay: 2
    channels: # List of channel names in order. If TI is suffix, only one PV is made; for others all PID PVS are made. None indicates an empty channel. Value is output channel
        - Coolant
        - Coolant_B_TI
        - Evaporator
        - Evaporator_B_TI
    out_channels:
        Coolant: 1
        Evaporator: 2
    heater_resistance:  # Heaters for channels 1 and 2. First element is nominal as set (25 or 50), second is true as measured.
        - [25, 24]
        - [50, 58]

pmd_301:
    module: 'devices.pmd301'
    autostart: True
    # ip: '0.0.0.0'
    port: 'COM4'
    timeout: 1
    delay: 5
    channels:   # list of "axes" in order. None indicates unused channel.
        - Ribbon
        - None
    locations:    # dict of preset locations (name then degrees from home) defaults for each channel
        Ribbon:
            - [0, 970]
            - [1, 1940]
            - [2, 2910]
            - [3, 3880]
            - [4, 4850]
            - [5, 5820]
            - [6, 6790]
    check_home:    # should it run the home routine before each move
        Ribbon: False
